Create A Training Climatology Table
- Using the existing iSWAI_HistoryData.csv to compute typical values by month and hour
- This gives you a “normal expected temp/humidity/etc” for each hour of the year.

In [1]:
import pandas as pd

HIST_PATH = "../dataset/iSWAI_HistoryData.csv"  # adjust
OUT_PATH = "../server/data/climatology_month_hour.csv"

df = pd.read_csv(HIST_PATH)
df["datetime"] = pd.to_datetime(df["datetime"], errors="coerce")
df = df.dropna(subset=["datetime"])

df["month"] = df["datetime"].dt.month
df["hour"] = df["datetime"].dt.hour
df

,name,datetime,temp,humidity,precip,windgust,windspeed,winddir,sealevelpressure,cloudcover,visibility,stations,source,month,hour
0,"talisay, daanbantayan, cebu",2022-01-01 00:00:00,25.9,80.56,4.0,43.9,30.2,34.5,1015.0,100.0,NaN,remote,obs,1,0
1,"talisay, daanbantayan, cebu",2022-01-01 01:00:00,25.9,81.05,3.8,44.6,28.8,34.2,1014.0,100.0,NaN,remote,obs,1,1
2,"talisay, daanbantayan, cebu",2022-01-01 02:00:00,26.1,80.59,2.8,56.9,31.0,40.2,1014.0,100.0,NaN,remote,obs,1,2
3,"talisay, daanbantayan, cebu",2022-01-01 03:00:00,26.6,79.20,4.7,43.2,34.2,49.2,1013.0,100.0,NaN,remote,obs,1,3
4,"talisay, daanbantayan, cebu",2022-01-01 04:00:00,26.6,79.20,3.1,48.2,38.5,60.7,1013.0,100.0,NaN,remote,obs,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35059,"talisay, daanbantayan, cebu",2025-12-31 19:00:00,27.6,82.74,0.0,18.4,11.9,13.0,1007.0,98.7,NaN,remote,obs,12,19
35060,"talisay, daanbantayan, cebu",2025-12-31 20:00:00,27.6,82.74,0.1,18.4,12.6,20.3,1008.0,100.0,NaN,remote,obs,12,20
35061,"talisay, daanbantayan, cebu",2025-12-31 21:00:00,27.5,83.23,0.1,17.6,11.5,30.4,1009.0,99.9,NaN,remote,obs,12,21
35062,"talisay, daanbantayan, cebu",2025-12-31 22:00:00,27.1,86.23,0.5,17.3,11.5,34.0,1009.0,99.1,NaN,remote,obs,12,22
35063,"talisay, daanbantayan, cebu",2025-12-31 23:00:00,26.7,89.34,1.0,15.1,12.2,46.0,1009.0,100.0,NaN,remote,obs,12,23

In [2]:
weather_cols = ["temp","humidity","precip","windgust","windspeed", "winddir","sealevelpressure","cloudcover","visibility"]
weather_cols = [c for c in weather_cols if c in df.columns]
weather_cols

['temp',
 'humidity',
 'precip',
 'windgust',
 'windspeed',
 'winddir',
 'sealevelpressure',
 'cloudcover',
 'visibility']

Grouping all the months and hours by getting each mean of column.

In [3]:
clim = (
    df.groupby(["month","hour"], as_index=False)[weather_cols]
      .mean()
)

In [4]:
clim

,month,hour,temp,humidity,precip,windgust,windspeed,winddir,sealevelpressure,cloudcover,visibility
0,1,0,26.710484,82.899516,0.233065,33.165323,25.491935,50.443548,1011.685484,74.941935,22.919048
1,1,1,26.617742,83.252903,0.241129,32.892742,25.304839,52.099194,1011.104839,74.242742,23.228571
2,1,2,26.521774,83.570081,0.245968,33.010484,25.128226,53.341935,1010.516129,76.073387,23.366667
3,1,3,26.457258,83.773790,0.333065,34.245161,25.031452,51.238710,1010.274194,76.396774,22.100000
4,1,4,26.426613,83.875000,0.333871,34.395161,25.023387,52.773387,1010.290323,76.997581,23.238095
...,...,...,...,...,...,...,...,...,...,...,...
283,12,19,27.873387,81.313710,0.227419,28.672581,19.362097,67.945968,1009.649194,80.292742,9.935484
284,12,20,27.746774,81.793710,0.257266,29.166129,19.895161,71.826613,1010.181452,80.151613,10.122581
285,12,21,27.643548,82.123468,0.225806,29.129839,19.979032,83.564516,1010.556452,79.833871,9.951613
286,12,22,27.538710,82.686694,0.231452,29.102419,19.576613,95.477419,1010.596774,79.333065,9.967742
287,12,23,27.421774,83.208387,0.323387,28.587903,19.506452,103.837903,1010.387903,80.354839,9.903226

In [5]:
clim.to_csv(OUT_PATH, index=False)
print("Saved:", OUT_PATH, "rows:", len(clim))

Saved: ../server/data/climatology_month_hour.csv rows: 288

Make a 2026 hourly timeline dataset
- By building a base 2026 Dataframe

In [6]:
import pandas as pd

dt = pd.date_range("2026-01-01 00:00:00", "2026-12-31 23:00:00", freq="h")
df_2026 = pd.DataFrame({"datetime": dt})
df_2026

                datetime
0    2026-01-01 00:00:00
1    2026-01-01 01:00:00
2    2026-01-01 02:00:00
3    2026-01-01 03:00:00
4    2026-01-01 04:00:00
...                  ...
8755 2026-12-31 19:00:00
8756 2026-12-31 20:00:00
8757 2026-12-31 21:00:00
8758 2026-12-31 22:00:00
8759 2026-12-31 23:00:00

[8760 rows x 1 columns]

- Using the existing df_2026 to compute typical values by month and hour
- This gives you a “normal expected temp/humidity/etc” for each hour of the year.

In [7]:
df_2026["month"] = df_2026["datetime"].dt.month
df_2026["hour"] = df_2026["datetime"].dt.hour
df_2026

                datetime  month  hour
0    2026-01-01 00:00:00      1     0
1    2026-01-01 01:00:00      1     1
2    2026-01-01 02:00:00      1     2
3    2026-01-01 03:00:00      1     3
4    2026-01-01 04:00:00      1     4
...                  ...    ...   ...
8755 2026-12-31 19:00:00     12    19
8756 2026-12-31 20:00:00     12    20
8757 2026-12-31 21:00:00     12    21
8758 2026-12-31 22:00:00     12    22
8759 2026-12-31 23:00:00     12    23

[8760 rows x 3 columns]

Merge climatology and df_2026 to fill temp/humidity/etc.

In [8]:
clim = pd.read_csv("../server/data/climatology_month_hour.csv")
df_2026 = df_2026.merge(clim, on=["month","hour"], how="left")
df_2026

,datetime,month,hour,temp,humidity,precip,windgust,windspeed,winddir,sealevelpressure,cloudcover,visibility
0,2026-01-01 00:00:00,1,0,26.710484,82.899516,0.233065,33.165323,25.491935,50.443548,1011.685484,74.941935,22.919048
1,2026-01-01 01:00:00,1,1,26.617742,83.252903,0.241129,32.892742,25.304839,52.099194,1011.104839,74.242742,23.228571
2,2026-01-01 02:00:00,1,2,26.521774,83.570081,0.245968,33.010484,25.128226,53.341935,1010.516129,76.073387,23.366667
3,2026-01-01 03:00:00,1,3,26.457258,83.773790,0.333065,34.245161,25.031452,51.238710,1010.274194,76.396774,22.100000
4,2026-01-01 04:00:00,1,4,26.426613,83.875000,0.333871,34.395161,25.023387,52.773387,1010.290323,76.997581,23.238095
...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2026-12-31 19:00:00,12,19,27.873387,81.313710,0.227419,28.672581,19.362097,67.945968,1009.649194,80.292742,9.935484
8756,2026-12-31 20:00:00,12,20,27.746774,81.793710,0.257266,29.166129,19.895161,71.826613,1010.181452,80.151613,10.122581
8757,2026-12-31 21:00:00,12,21,27.643548,82.123468,0.225806,29.129839,19.979032,83.564516,1010.556452,79.833871,9.951613
8758,2026-12-31 22:00:00,12,22,27.538710,82.686694,0.231452,29.102419,19.576613,95.477419,1010.596774,79.333065,9.967742
8759,2026-12-31 23:00:00,12,23,27.421774,83.208387,0.323387,28.587903,19.506452,103.837903,1010.387903,80.354839,9.903226

REMOVING THE COLUMNS pred_timestamp, pred_windspeed, and pred_winddir from iswai_data of supabase

In [18]:
# Input CSV
input_file = "../server/input/iswai_data_rows.csv"

# Output CSV
output_file = "../server/input/iswai_data_rows_clean.csv"

# Read CSV
df = pd.read_csv(input_file)

# Columns to remove
cols_to_remove = ["pred_timestamp", "pred_windspeed", "pred_winddir"]

# Drop columns if they exist
df = df.drop(columns=[c for c in cols_to_remove if c in df.columns])

# Save cleaned CSV
df.to_csv(output_file, index=False)

print("Columns removed successfully!")
print("Saved cleaned file as:", output_file)

Columns removed successfully!
Saved cleaned file as: ../server/input/iswai_data_rows_clean.csv

MERGE ACTUALS ESP32 Records to df_2026 climatology

In [ ]:
esp = pd.read_csv("../server/input/2026_climatology.csv")
esp["datetime"] = pd.to_datetime(esp["datetime"], errors="coerce")
esp

,datetime,temp,humidity,precip,windgust,windspeed,winddir,sealevelpressure,cloudcover,visibility
0,2026-01-01 00:00:00,26.6,88.80,0.8,14.8,12.6,49.4,1008.0,100.0,NaN
1,2026-01-01 01:00:00,26.7,87.23,0.2,15.5,11.9,47.7,1008.0,98.1,NaN
2,2026-01-01 02:00:00,26.7,87.23,0.2,16.6,11.5,45.0,1007.0,99.5,NaN
3,2026-01-01 03:00:00,26.3,88.78,0.5,17.3,11.2,43.4,1007.0,99.0,NaN
4,2026-01-01 04:00:00,26.1,89.83,0.2,17.6,11.2,45.0,1008.0,98.4,NaN
...,...,...,...,...,...,...,...,...,...,...
1699,2026-03-12 19:00:00,26.5,66.00,0.0,32.5,29.3,12.5,1009.0,62.2,24.1
1700,2026-03-12 20:00:00,26.5,65.86,0.0,33.1,28.8,17.2,1010.0,85.5,24.1
1701,2026-03-12 21:00:00,26.2,68.30,0.0,32.8,28.2,21.1,1010.0,63.6,24.1
1702,2026-03-12 22:00:00,25.9,70.83,0.0,32.4,27.6,25.1,1010.0,41.7,24.1
1703,2026-03-12 23:00:00,25.7,73.46,0.0,32.0,27.0,29.0,1010.0,19.8,24.1

Columns might include: datetime, windspeed, winddir, temp, humidity, ...

In [20]:
df_2026 = df_2026.merge(esp, on="datetime", how="left", suffixes=("", "_esp"))
df_2026

,datetime,month,hour,temp,humidity,precip,windgust,sealevelpressure,cloudcover,visibility,temp_esp,humidity_esp,precip_esp,windgust_esp,windspeed,winddir,sealevelpressure_esp,cloudcover_esp,visibility_esp
0,2026-01-01 00:00:00,1,0,26.710484,82.899516,0.233065,33.165323,1011.685484,74.941935,22.919048,26.6,88.80,0.8,14.8,12.6,49.4,1008.0,100.0,NaN
1,2026-01-01 01:00:00,1,1,26.617742,83.252903,0.241129,32.892742,1011.104839,74.242742,23.228571,26.7,87.23,0.2,15.5,11.9,47.7,1008.0,98.1,NaN
2,2026-01-01 02:00:00,1,2,26.521774,83.570081,0.245968,33.010484,1010.516129,76.073387,23.366667,26.7,87.23,0.2,16.6,11.5,45.0,1007.0,99.5,NaN
3,2026-01-01 03:00:00,1,3,26.457258,83.773790,0.333065,34.245161,1010.274194,76.396774,22.100000,26.3,88.78,0.5,17.3,11.2,43.4,1007.0,99.0,NaN
4,2026-01-01 04:00:00,1,4,26.426613,83.875000,0.333871,34.395161,1010.290323,76.997581,23.238095,26.1,89.83,0.2,17.6,11.2,45.0,1008.0,98.4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2026-12-31 19:00:00,12,19,27.873387,81.313710,0.227419,28.672581,1009.649194,80.292742,9.935484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8756,2026-12-31 20:00:00,12,20,27.746774,81.793710,0.257266,29.166129,1010.181452,80.151613,10.122581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8757,2026-12-31 21:00:00,12,21,27.643548,82.123468,0.225806,29.129839,1010.556452,79.833871,9.951613,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8758,2026-12-31 22:00:00,12,22,27.538710,82.686694,0.231452,29.102419,1010.596774,79.333065,9.967742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8759,2026-12-31 23:00:00,12,23,27.421774,83.208387,0.323387,28.587903,1010.387903,80.354839,9.903226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Override Climatology with real esp values when present.

In [29]:
for col in ["temp","humidity","precip","windgust","sealevelpressure","cloudcover","visibility"]:
    esp_col = f"{col}_esp"
    if esp_col in df_2026.columns:
        df_2026[col] = df_2026[esp_col].combine_first(df_2026[col])
        df_2026.drop(columns=[esp_col], inplace=True)

df_2026

,datetime,month,hour,temp,humidity,precip,windgust,sealevelpressure,cloudcover,visibility,...,wind_lag_24,gust_lag_24,wind_roll_mean_3,wind_roll_std_3,wind_roll_mean_6,wind_roll_std_6,wind_roll_mean_12,wind_roll_std_12,wind_roll_mean_24,wind_roll_std_24
0,2026-01-01 00:00:00,1,0,26.600000,88.800000,0.800000,14.800000,1008.000000,100.000000,22.919048,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-01-01 01:00:00,1,1,26.700000,87.230000,0.200000,15.500000,1008.000000,98.100000,23.228571,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-01-01 02:00:00,1,2,26.700000,87.230000,0.200000,16.600000,1007.000000,99.500000,23.366667,...,NaN,NaN,12.000000,0.556776,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-01-01 03:00:00,1,3,26.300000,88.780000,0.500000,17.300000,1007.000000,99.000000,22.100000,...,NaN,NaN,11.533333,0.351188,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-01-01 04:00:00,1,4,26.100000,89.830000,0.200000,17.600000,1008.000000,98.400000,23.238095,...,NaN,NaN,11.300000,0.173205,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2026-12-31 19:00:00,12,19,27.873387,81.313710,0.227419,28.672581,1009.649194,80.292742,9.935484,...,NaN,28.672581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8756,2026-12-31 20:00:00,12,20,27.746774,81.793710,0.257266,29.166129,1010.181452,80.151613,10.122581,...,NaN,29.166129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8757,2026-12-31 21:00:00,12,21,27.643548,82.123468,0.225806,29.129839,1010.556452,79.833871,9.951613,...,NaN,29.129839,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8758,2026-12-31 22:00:00,12,22,27.538710,82.686694,0.231452,29.102419,1010.596774,79.333065,9.967742,...,NaN,29.102419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8759,2026-12-31 23:00:00,12,23,27.421774,83.208387,0.323387,28.587903,1010.387903,80.354839,9.903226,...,NaN,28.587903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Saving the Climatology CSV

In [30]:
df_2026.to_csv("../server/data/2026.csv", index=False)
print("Saved 2026 data with climatology and ESP values.")

Saved 2026 data with climatology and ESP values.

Add DateTime Cyclical Features

In [ ]:
import numpy as np  
def add_datetime_features(df):
    df = df.copy()
    df["datetime"] = pd.to_datetime(df["datetime"], errors="coerce")
    df = df.sort_values("datetime").reset_index(drop=True)

    df["hour"] = df["datetime"].dt.hour
    df["dayofweek"] = df["datetime"].dt.dayofweek
    df["month"] = df["datetime"].dt.month
    df["day"] = df["datetime"].dt.day

    df["hour_sin"] = np.sin(2*np.pi*df["hour"]/24)
    df["hour_cos"] = np.cos(2*np.pi*df["hour"]/24)
    df["month_sin"] = np.sin(2*np.pi*df["month"]/12)
    df["month_cos"] = np.cos(2*np.pi*df["month"]/12)
    return df

df_2026 = add_datetime_features(df_2026)
df_2026 = df_2026.sort_values("datetime").reset_index(drop=True)
df_2026

,datetime,month,hour,temp,humidity,precip,windgust,sealevelpressure,cloudcover,visibility,...,wind_lag_24,gust_lag_24,wind_roll_mean_3,wind_roll_std_3,wind_roll_mean_6,wind_roll_std_6,wind_roll_mean_12,wind_roll_std_12,wind_roll_mean_24,wind_roll_std_24
0,2026-01-01 00:00:00,1,0,26.600000,88.800000,0.800000,14.800000,1008.000000,100.000000,22.919048,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-01-01 01:00:00,1,1,26.700000,87.230000,0.200000,15.500000,1008.000000,98.100000,23.228571,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-01-01 02:00:00,1,2,26.700000,87.230000,0.200000,16.600000,1007.000000,99.500000,23.366667,...,NaN,NaN,12.000000,0.556776,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-01-01 03:00:00,1,3,26.300000,88.780000,0.500000,17.300000,1007.000000,99.000000,22.100000,...,NaN,NaN,11.533333,0.351188,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-01-01 04:00:00,1,4,26.100000,89.830000,0.200000,17.600000,1008.000000,98.400000,23.238095,...,NaN,NaN,11.300000,0.173205,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2026-12-31 19:00:00,12,19,27.873387,81.313710,0.227419,28.672581,1009.649194,80.292742,9.935484,...,NaN,28.672581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8756,2026-12-31 20:00:00,12,20,27.746774,81.793710,0.257266,29.166129,1010.181452,80.151613,10.122581,...,NaN,29.166129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8757,2026-12-31 21:00:00,12,21,27.643548,82.123468,0.225806,29.129839,1010.556452,79.833871,9.951613,...,NaN,29.129839,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8758,2026-12-31 22:00:00,12,22,27.538710,82.686694,0.231452,29.102419,1010.596774,79.333065,9.967742,...,NaN,29.102419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8759,2026-12-31 23:00:00,12,23,27.421774,83.208387,0.323387,28.587903,1010.387903,80.354839,9.903226,...,NaN,28.587903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Recursive wind speed direction

In [33]:
import joblib
import numpy as np

ws = joblib.load("../server/models/windspeed_model.joblib")
rf = ws["rf"]
xgb_model = ws["xgb"]
feature_cols = ws["feature_cols"]
w = ws.get("weights", {"rf": 0.5, "xgb": 0.5})

def add_lag_roll_features(df) :
    df = df.copy()
    df = df.sort_values("datetime").reset_index(drop=True)

    # Lags for windspeed and windgust
    wind_lags = [1, 2, 3, 6, 12, 24]
    gust_lags = [1, 2, 3, 6, 12, 24]

    for lag in wind_lags:
        df[f"wind_lag_{lag}"] = df["windspeed"].shift(lag)

    for lag in gust_lags:
        df[f"gust_lag_{lag}"] = df["windgust"].shift(lag)

    # Rolling stats (use previous values, shift(1) to prevent leakage)
    windows = [3, 6, 12, 24]
    for w in windows:
        df[f"wind_roll_mean_{w}"] = df["windspeed"].shift(1).rolling(w).mean()
        df[f"wind_roll_std_{w}"]  = df["windspeed"].shift(1).rolling(w).std()

    return df

# start with existing windspeed (ESP32) if available, else NaN
df_2026["windspeed"] = pd.to_numeric(df_2026.get("windspeed"), errors="coerce")
df_2026 = add_lag_roll_features(df_2026)

for i in range(len(df_2026)):
    if pd.notna(df_2026.loc[i, "windspeed"]):
        continue

    row = df_2026.loc[i, feature_cols]
    if row.isna().any():
        continue

    X = row.to_numpy().reshape(1, -1)
    pred = w["rf"] * rf.predict(X)[0] + w["xgb"] * xgb_model.predict(X)[0]
    df_2026.loc[i, "windspeed"] = float(pred)

    # update lags
    df_2026 = add_lag_roll_features(df_2026)

Export Wind Speed Prediction for Vite Timeline Chart

In [35]:
# include both actual (if any) and prediction line
df_speed_out = df_2026[["datetime", "windspeed"]].copy()
df_speed_out.rename(columns={"windspeed": "pred_windspeed"}, inplace=True)
df_speed_out.to_csv("../server/output/windspeed_2026_pred.csv", index=False)